from pathlib import Path

p = Path('live_08.txt')
s = p.read_text(encoding='utf-8')
old = "st.ses=session;let authRefreshTimer=null;S.auth.onAuthStateChange((ev,s)=>{st.ses=s;if(!s){clearTimeout(authRefreshTimer);render();return}if(ev==='SIGNED_IN'&&app.querySelector('.auth')){app.innerHTML='<main class=\"auth\"><section class=\"card\"><div class=\"mark bigmark\">◇</div><div class=\"eyebrow\">OTURUM AÇILDI</div><h2>Masa hazırlanıyor…</h2><p class=\"muted\">Karakter ve oyun verileri yükleniyor.</p></section></main>';clearTimeout(authRefreshTimer);authRefreshTimer=setTimeout(()=>{if(st.ses?.user?.id===s.user.id)refresh()},0)}});\nif(authBootTimedOut){st.ses=null;render();const card=app.querySelector('.auth .card');if(card){const recovery=document.createElement('div');recovery.className='notice';recovery.innerHTML='<b>Oturum kontrolü yanıt vermedi.</b><p>Tarayıcıda eski veya kilitlenmiş bir oturum kalmış olabilir. Aşağıdaki düğme yalnızca bu siteye ait yerel oturum kaydını temizleyip sayfayı yeniden açar.</p><button type=\"button\" id=\"catlak-auth-recover\">Oturumu Temizle ve Yeniden Aç</button>';card.appendChild(recovery);const recover=document.querySelector('#catlak-auth-recover');if(recover)recover.addEventListener('click',()=>{try{localStorage.removeItem('sb-ygbereitlhjvoqgqlwfe-auth-token');localStorage.removeItem('sb-ygbereitlhjvoqgqlwfe-auth-token-user')}catch{}location.reload()});}msg('Oturum kontrolü zaman aşımına uğradı.');}else if(session)await refresh();else render();catReady.then(()=>{if(st.ses)refresh();else if(!authBootTimedOut)render()}).catch(()=>{});"
new = """st.ses=session;let authRefreshTimer=null,catlakRefreshRun=null,catlakRefreshAgain=false;
async function catlakSafeRefresh(){if(!st.ses?.user){render();return}if(catlakRefreshRun){catlakRefreshAgain=true;return catlakRefreshRun}const uid=st.ses.user.id;catlakRefreshRun=(async()=>{try{await Promise.race([refresh(),new Promise((_,reject)=>setTimeout(()=>reject(new Error('Oyun verileri zaman aşımına uğradı. Lütfen tekrar dene.')),12000))])}catch(e){console.error('CATLAK_REFRESH_ERROR',e);if(st.ses?.user?.id===uid){app.innerHTML='<main class=\"auth\"><section class=\"card\"><div class=\"mark bigmark\">◇</div><div class=\"eyebrow\">BAĞLANTI KURULDU</div><h2>Oyun verileri yüklenemedi</h2><p class=\"muted\">Oturum açıldı fakat masa verileri zamanında alınamadı. Yeniden denemek için aşağıdaki düğmeyi kullan.</p><button class=\"primary widebtn\" id=\"catlak-refresh-retry\">Masa Verilerini Yeniden Yükle</button><button class=\"widebtn\" id=\"catlak-refresh-logout\">Çıkış Yap</button></section></main>';document.querySelector('#catlak-refresh-retry')?.addEventListener('click',()=>setTimeout(()=>catlakSafeRefresh(),0));document.querySelector('#catlak-refresh-logout')?.addEventListener('click',()=>S.auth.signOut());msg(e.message||'Oyun verileri yüklenemedi.')}}})();try{return await catlakRefreshRun}finally{catlakRefreshRun=null;if(catlakRefreshAgain&&st.ses?.user){catlakRefreshAgain=false;setTimeout(()=>catlakSafeRefresh(),150)}}}
S.auth.onAuthStateChange((ev,s)=>{st.ses=s;if(!s){clearTimeout(authRefreshTimer);render();return}if((ev==='SIGNED_IN'||ev==='INITIAL_SESSION'||ev==='TOKEN_REFRESHED')&&app.querySelector('.auth')){app.innerHTML='<main class=\"auth\"><section class=\"card\"><div class=\"mark bigmark\">◇</div><div class=\"eyebrow\">OTURUM AÇILDI</div><h2>Masa hazırlanıyor…</h2><p class=\"muted\">Karakter ve oyun verileri yükleniyor.</p></section></main>';clearTimeout(authRefreshTimer);authRefreshTimer=setTimeout(()=>{if(st.ses?.user?.id===s.user.id)catlakSafeRefresh()},0)}});
if(authBootTimedOut){st.ses=null;render();const card=app.querySelector('.auth .card');if(card){const recovery=document.createElement('div');recovery.className='notice';recovery.innerHTML='<b>Oturum kontrolü yanıt vermedi.</b><p>Tarayıcıda eski veya kilitlenmiş bir oturum kalmış olabilir. Aşağıdaki düğme yalnızca bu siteye ait yerel oturum kaydını temizleyip sayfayı yeniden açar.</p><button type=\"button\" id=\"catlak-auth-recover\">Oturumu Temizle ve Yeniden Aç</button>';card.appendChild(recovery);const recover=document.querySelector('#catlak-auth-recover');if(recover)recover.addEventListener('click',()=>{try{Object.keys(localStorage).filter(k=>/^sb-.*-auth-token$/i.test(k)).forEach(k=>localStorage.removeItem(k))}catch{}location.reload()});}msg('Oturum kontrolü zaman aşımına uğradı.');}else if(session)await catlakSafeRefresh();else render();catReady.then(()=>{if(st.ses)catlakSafeRefresh();else if(!authBootTimedOut)render()}).catch(()=>{});"""
if old not in s:
    raise SystemExit('auth/refresh block not found; source changed unexpectedly')
s = s.replace(old, new, 1)
s = s.replace("liveRefreshTimer=setTimeout(()=>{if(st.ses)refresh()},180)", "liveRefreshTimer=setTimeout(()=>{if(st.ses)catlakSafeRefresh()},180)", 1)
p.write_text(s, encoding='utf-8')
print('auth/refresh hardening applied')
